FROM python:3.10-alpine

RUN mkdir -p /home/app

WORKDIR /home/app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app.main_api:app", "--host=0.0.0.0", "--port=8000", "--reload"]